# Generated by Django 2.2.1 on 2019-05-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipInfo',
            fields=[
                ('eunit', models.CharField(max_length=50)),
                ('enum', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('etype', models.CharField(max_length=50)),
                ('especs', models.CharField(max_length=50)),
                ('ecost', models.CharField(max_length=50)),
                ('euser', models.CharField(max_length=50)),
                ('elocate', models.CharField(max_length=50)),
                ('ecompany', models.CharField(max_length=50)),
                ('efacnum', models.CharField(max_length=50)),
                ('epuchasedate', models.DateField(max_length=6)),
                ('estatus', models.CharField(max_length=50)),
                ('esbuject', models.CharField(max_length=50)),
                ('eusedir', models.CharField(max_length=50)),
                ('esource', models.CharField(max_length=50)),
                ('estordate', models.DateField(max_length=6)),
                ('esupplier', models.DateField(max_length=6)),
                ('einvoicenum', models.CharField(max_length=50)),
                ('eclassnum', models.CharField(max_length=50)),
                ('eremarks', models.CharField(max_length=200)),
                ('epromethod', models.CharField(max_length=50)),
                ('eusernum', models.DateField(max_length=6)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'equipinfo',
            },
        ),
    ]
