# Generated by Django 2.2.1 on 2019-05-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipinfo',
            name='esupplier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipinfo',
            name='eusernum',
            field=models.CharField(max_length=50),
        ),
    ]
