# Generated by Django 2.2.1 on 2019-06-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equapi', '0003_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='equ',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='equapi.EquipInfo'),
            preserve_default=False,
        ),
    ]
