# Generated by Django 2.2.1 on 2019-06-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equapi', '0004_userinfo_equ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='equ',
        ),
    ]
