# Generated by Django 2.2.1 on 2019-06-09 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equapi', '0005_remove_userinfo_equ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipinfo',
            name='eusernum',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='equapi.UserInfo'),
        ),
    ]
