# Generated by Django 2.2.1 on 2019-06-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equapi', '0006_auto_20190609_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='123', max_length=12),
        ),
    ]
