# Generated by Django 2.2.1 on 2019-06-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equapi', '0007_userinfo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
