# Generated by Django 2.2.1 on 2019-07-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equapi', '0009_userinfo_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=50)),
                ('ownernum', models.CharField(max_length=50)),
                ('borrowname', models.CharField(max_length=50)),
                ('borrownum', models.CharField(max_length=50)),
                ('starttime', models.DateField(max_length=6)),
                ('endtime', models.DateField(max_length=6)),
                ('isactive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'borrowuser',
            },
        ),
    ]
