# Generated by Django 2.2.1 on 2019-07-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equapi', '0010_borrowuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowuser',
            name='equipname',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowuser',
            name='equipnum',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
